name: omnia
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3
  - python_abi=3.10
  - pip:
      - appdirs==1.4.4
      - comoda==0.4.2
      - python-magic==0.4.27
      - mongoengine==0.24.2
