name: omnia
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3
  - pip:
      - pre-commit==2.20
      - black==22.10
      - flake8==5.0
      - isort==5.10
      - interrogate==1.5
      - mongomock==4.1.2
