# MongoDB connection
mdbc:
  alias_label: "omnia"
  username: "username"
  password: "password"
  hostname: "hostname"

# Logger details
loglevel: "INFO"
logformat: "%(asctime)s|%(levelname)-8s|%(name)s |%(module)s |%(message)s"


