# MongoDB connection
mdbc:
  alias_label: "omnia_dv_alias"
  username: "username"
  password: "password"
  hostname: "hostname"
  port: 27017
  db: "omnia_dv"
  auth_mech: "SCRAM-SHA-256"
  auth_source: "omnia_dv"

# Logger details
loglevel: "INFO"
logformat: "%(asctime)s|%(levelname)-8s|%(name)s |%(module)s |%(message)s"


