name: omnia

on: [push,pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: omnia
          environment-file: base_environment.yml
          auto-update-conda: true
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        shell: bash -el {0}
        run: |
          make dependencies_dev
          make install

      - name: Test version
        shell: bash -el {0}
        run: |
          make test
